<?php

return [
    'schema' => [
        'site_name' => ['type' => 'string', 'group' => 'general'],
        'site_tagline' => ['type' => 'string', 'group' => 'general'],
        'site_logo' => ['type' => 'string', 'group' => 'general'],
        'site_favicon' => ['type' => 'string', 'group' => 'general'],
        'site_address' => ['type' => 'string', 'group' => 'general'],
        'contact_email' => ['type' => 'string', 'group' => 'support'],
        'support_phone' => ['type' => 'string', 'group' => 'support'],
        'support_faqs' => ['type' => 'json', 'group' => 'support'],
        'site_currency' => ['type' => 'string', 'group' => 'general'],
        'site_currency_symbol' => ['type' => 'string', 'group' => 'general'],
        'social_facebook' => ['type' => 'string', 'group' => 'general'],
        'social_instagram' => ['type' => 'string', 'group' => 'general'],
        'social_twitter' => ['type' => 'string', 'group' => 'general'],
        'social_whatsapp' => ['type' => 'string', 'group' => 'general'],
        'social_youtube' => ['type' => 'string', 'group' => 'general'],
        'app_google_play_url' => ['type' => 'string', 'group' => 'general'],
        'app_store_url' => ['type' => 'string', 'group' => 'general'],
        'maintenance_mode' => ['type' => 'boolean', 'group' => 'general'],
        'maintenance_title' => ['type' => 'string', 'group' => 'general'],
        'maintenance_message' => ['type' => 'string', 'group' => 'general'],
        'home_banner_mode' => ['type' => 'string', 'group' => 'general'],
        'home_banner_image_url' => ['type' => 'string', 'group' => 'general'],
        'home_banner_images' => ['type' => 'json', 'group' => 'general'],
        'home_banner_image_positions' => ['type' => 'json', 'group' => 'general'],
        'home_banner_image_fits' => ['type' => 'json', 'group' => 'general'],
        'home_banner_display_seconds' => ['type' => 'integer', 'group' => 'general'],
        'app_banner_images' => ['type' => 'json', 'group' => 'general'],
        'app_banner_display_seconds' => ['type' => 'integer', 'group' => 'general'],
        'home_banner_slide_1_badge' => ['type' => 'string', 'group' => 'general'],
        'home_banner_slide_1_title' => ['type' => 'string', 'group' => 'general'],
        'home_banner_slide_1_desc' => ['type' => 'string', 'group' => 'general'],
        'home_banner_slide_2_badge' => ['type' => 'string', 'group' => 'general'],
        'home_banner_slide_2_title' => ['type' => 'string', 'group' => 'general'],
        'home_banner_slide_2_desc' => ['type' => 'string', 'group' => 'general'],
        'home_banner_slide_3_badge' => ['type' => 'string', 'group' => 'general'],
        'home_banner_slide_3_title' => ['type' => 'string', 'group' => 'general'],
        'home_banner_slide_3_desc' => ['type' => 'string', 'group' => 'general'],
        'listing_moderation_enabled' => ['type' => 'boolean', 'group' => 'listings'],
        'listing_allow_guest_view' => ['type' => 'boolean', 'group' => 'listings'],
        'listing_expiry_days' => ['type' => 'integer', 'group' => 'listings'],
        'listing_max_images' => ['type' => 'integer', 'group' => 'listings'],
        'listing_max_per_user' => ['type' => 'integer', 'group' => 'listings'],
        'listing_description_min' => ['type' => 'integer', 'group' => 'listings'],
        'listing_price_required' => ['type' => 'boolean', 'group' => 'listings'],
        'listing_location_required' => ['type' => 'boolean', 'group' => 'listings'],
        'listing_allow_negotiation' => ['type' => 'boolean', 'group' => 'listings'],
        'listing_auto_renew' => ['type' => 'boolean', 'group' => 'listings'],
        'listing_allow_bump' => ['type' => 'boolean', 'group' => 'listings'],
        'location_nearby_radius_km' => ['type' => 'integer', 'group' => 'listings'],
        'location_default_country' => ['type' => 'string', 'group' => 'listings'],
        'free_call_access_limit' => ['type' => 'integer', 'group' => 'listings'],
        'free_map_access_limit' => ['type' => 'integer', 'group' => 'listings'],
        'google_maps_api_key' => ['type' => 'secret', 'group' => 'listings'],
        'featured_daily_rate' => ['type' => 'integer', 'group' => 'featured'],
        'featured_allowed_days' => ['type' => 'json', 'group' => 'featured'],
        'payment_gateway' => ['type' => 'string', 'group' => 'featured'],
        'payment_checkout_mode' => ['type' => 'string', 'group' => 'featured'],
        'payment_gateway_selection_mode' => ['type' => 'string', 'group' => 'featured'],
        'payment_currency' => ['type' => 'string', 'group' => 'featured'],
        'payment_test_mode' => ['type' => 'boolean', 'group' => 'featured'],
        'razorpay_key_id' => ['type' => 'string', 'group' => 'featured'],
        'razorpay_key_secret' => ['type' => 'secret', 'group' => 'featured'],
        'razorpay_base_url' => ['type' => 'string', 'group' => 'featured'],
        'phonepe_merchant_id' => ['type' => 'string', 'group' => 'featured'],
        'phonepe_salt_key' => ['type' => 'secret', 'group' => 'featured'],
        'phonepe_salt_index' => ['type' => 'string', 'group' => 'featured'],
        'phonepe_base_url' => ['type' => 'string', 'group' => 'featured'],
        'paytm_mid' => ['type' => 'string', 'group' => 'featured'],
        'paytm_merchant_key' => ['type' => 'secret', 'group' => 'featured'],
        'paytm_website' => ['type' => 'string', 'group' => 'featured'],
        'paytm_base_url' => ['type' => 'string', 'group' => 'featured'],
        'registration_enabled' => ['type' => 'boolean', 'group' => 'registration'],
        'email_verification_required' => ['type' => 'boolean', 'group' => 'registration'],
        'phone_verification_required' => ['type' => 'boolean', 'group' => 'registration'],
        'auth_login_email_enabled' => ['type' => 'boolean', 'group' => 'registration'],
        'auth_login_mobile_enabled' => ['type' => 'boolean', 'group' => 'registration'],
        'auth_register_email_enabled' => ['type' => 'boolean', 'group' => 'registration'],
        'auth_register_mobile_enabled' => ['type' => 'boolean', 'group' => 'registration'],
        'firebase_auth_domain' => ['type' => 'string', 'group' => 'registration'],
        'google_oauth_enabled' => ['type' => 'boolean', 'group' => 'registration'],
        'google_oauth_client_id' => ['type' => 'string', 'group' => 'registration'],
        'google_oauth_client_secret' => ['type' => 'secret', 'group' => 'registration'],
        'facebook_oauth_enabled' => ['type' => 'boolean', 'group' => 'registration'],
        'facebook_oauth_app_id' => ['type' => 'string', 'group' => 'registration'],
        'facebook_oauth_app_secret' => ['type' => 'secret', 'group' => 'registration'],
        'notification_poll_seconds' => ['type' => 'integer', 'group' => 'notifications'],
        'notification_email_enabled' => ['type' => 'boolean', 'group' => 'notifications'],
        'notification_new_message' => ['type' => 'boolean', 'group' => 'notifications'],
        'notification_listing_approved' => ['type' => 'boolean', 'group' => 'notifications'],
        'notification_listing_expired' => ['type' => 'boolean', 'group' => 'notifications'],
        'notification_push_enabled' => ['type' => 'boolean', 'group' => 'notifications'],
        'notification_sound_url' => ['type' => 'string', 'group' => 'notifications'],
        'startup_popup_enabled' => ['type' => 'boolean', 'group' => 'notifications'],
        'startup_popup_title' => ['type' => 'string', 'group' => 'notifications'],
        'startup_popup_message' => ['type' => 'string', 'group' => 'notifications'],
        'startup_popup_image_url' => ['type' => 'string', 'group' => 'notifications'],
        'startup_popup_link_url' => ['type' => 'string', 'group' => 'notifications'],
        'startup_popup_button_label' => ['type' => 'string', 'group' => 'notifications'],
        'startup_popup_style' => ['type' => 'string', 'group' => 'notifications'],
        'startup_popup_open_new_tab' => ['type' => 'boolean', 'group' => 'notifications'],
        'fcm_api_key' => ['type' => 'secret', 'group' => 'notifications'],
        'fcm_project_id' => ['type' => 'string', 'group' => 'notifications'],
        'fcm_messaging_sender_id' => ['type' => 'string', 'group' => 'notifications'],
        'fcm_app_id' => ['type' => 'string', 'group' => 'notifications'],
        'fcm_vapid_key' => ['type' => 'string', 'group' => 'notifications'],
        'fcm_service_account_email' => ['type' => 'string', 'group' => 'notifications'],
        'fcm_service_account_private_key' => ['type' => 'secret', 'group' => 'notifications'],
        'fcm_server_key' => ['type' => 'secret', 'group' => 'notifications'],
        'twa_enabled' => ['type' => 'boolean', 'group' => 'twa'],
        'twa_name' => ['type' => 'string', 'group' => 'twa'],
        'twa_short_name' => ['type' => 'string', 'group' => 'twa'],
        'twa_description' => ['type' => 'string', 'group' => 'twa'],
        'twa_start_url' => ['type' => 'string', 'group' => 'twa'],
        'twa_scope' => ['type' => 'string', 'group' => 'twa'],
        'twa_display' => ['type' => 'string', 'group' => 'twa'],
        'twa_orientation' => ['type' => 'string', 'group' => 'twa'],
        'twa_theme_color' => ['type' => 'string', 'group' => 'twa'],
        'twa_background_color' => ['type' => 'string', 'group' => 'twa'],
        'twa_package_name' => ['type' => 'string', 'group' => 'twa'],
        'twa_sha256_fingerprints' => ['type' => 'json', 'group' => 'twa'],
        'twa_icon_url' => ['type' => 'string', 'group' => 'twa'],
        'twa_icon_maskable_url' => ['type' => 'string', 'group' => 'twa'],
        'twa_navigation_color' => ['type' => 'string', 'group' => 'twa'],
        'twa_splash_fade_duration' => ['type' => 'integer', 'group' => 'twa'],
        'twa_app_version_name' => ['type' => 'string', 'group' => 'twa'],
        'twa_app_version_code' => ['type' => 'integer', 'group' => 'twa'],
        'twa_min_sdk_version' => ['type' => 'integer', 'group' => 'twa'],
        'twa_signing_key_alias' => ['type' => 'string', 'group' => 'twa'],
        'twa_keystore_store_type' => ['type' => 'string', 'group' => 'twa'],
        'twa_keystore_password' => ['type' => 'secret', 'group' => 'twa'],
        'twa_key_password' => ['type' => 'secret', 'group' => 'twa'],
        'twa_key_full_name' => ['type' => 'string', 'group' => 'twa'],
        'twa_key_org' => ['type' => 'string', 'group' => 'twa'],
        'twa_key_org_unit' => ['type' => 'string', 'group' => 'twa'],
        'twa_key_country' => ['type' => 'string', 'group' => 'twa'],
        'twa_key_state' => ['type' => 'string', 'group' => 'twa'],
        'twa_key_city' => ['type' => 'string', 'group' => 'twa'],
        'twa_keystore_password' => ['type' => 'secret', 'group' => 'twa'],
        'twa_key_password' => ['type' => 'secret', 'group' => 'twa'],
        'twa_key_full_name' => ['type' => 'string', 'group' => 'twa'],
        'twa_key_org' => ['type' => 'string', 'group' => 'twa'],
        'twa_key_org_unit' => ['type' => 'string', 'group' => 'twa'],
        'twa_key_country' => ['type' => 'string', 'group' => 'twa'],
        'twa_key_state' => ['type' => 'string', 'group' => 'twa'],
        'twa_key_city' => ['type' => 'string', 'group' => 'twa'],
        'mail_driver' => ['type' => 'string', 'group' => 'email'],
        'mail_from_name' => ['type' => 'string', 'group' => 'email'],
        'mail_from_address' => ['type' => 'string', 'group' => 'email'],
        'mail_smtp_host' => ['type' => 'string', 'group' => 'email'],
        'mail_smtp_port' => ['type' => 'integer', 'group' => 'email'],
        'mail_smtp_username' => ['type' => 'string', 'group' => 'email'],
        'mail_smtp_password' => ['type' => 'secret', 'group' => 'email'],
        'mail_smtp_encryption' => ['type' => 'string', 'group' => 'email'],
        'mail_mailgun_domain' => ['type' => 'string', 'group' => 'email'],
        'mail_mailgun_secret' => ['type' => 'secret', 'group' => 'email'],
        'recaptcha_enabled' => ['type' => 'boolean', 'group' => 'security'],
        'recaptcha_version' => ['type' => 'string', 'group' => 'security'],
        'recaptcha_site_key' => ['type' => 'string', 'group' => 'security'],
        'recaptcha_secret_key' => ['type' => 'secret', 'group' => 'security'],
        'max_login_attempts' => ['type' => 'integer', 'group' => 'security'],
        'login_lockout_minutes' => ['type' => 'integer', 'group' => 'security'],
        'seo_meta_description' => ['type' => 'string', 'group' => 'marketing'],
        'seo_meta_keywords' => ['type' => 'string', 'group' => 'marketing'],
        'seo_robots' => ['type' => 'string', 'group' => 'marketing'],
        'seo_google_site_verification' => ['type' => 'string', 'group' => 'marketing'],
        'seo_bing_site_verification' => ['type' => 'string', 'group' => 'marketing'],
        'seo_google_analytics_id' => ['type' => 'string', 'group' => 'marketing'],
        'facebook_pixel_id' => ['type' => 'string', 'group' => 'marketing'],
        'og_image_url' => ['type' => 'string', 'group' => 'marketing'],
        'adsense_enabled' => ['type' => 'boolean', 'group' => 'marketing'],
        'adsense_client_id' => ['type' => 'string', 'group' => 'marketing'],
        'adsense_slot_id' => ['type' => 'string', 'group' => 'marketing'],
        'adsense_banner_slot_top' => ['type' => 'string', 'group' => 'marketing'],
        'adsense_banner_slot_bottom' => ['type' => 'string', 'group' => 'marketing'],
        'adsense_banner_slot_guest' => ['type' => 'string', 'group' => 'marketing'],
        'adsense_native_slot_id' => ['type' => 'string', 'group' => 'marketing'],
        'adsense_article_slot_id' => ['type' => 'string', 'group' => 'marketing'],
        'adsense_display_slot_id' => ['type' => 'string', 'group' => 'marketing'],
        'adsense_feed_rows_interval' => ['type' => 'integer', 'group' => 'marketing'],
        'adsense_locations' => ['type' => 'json', 'group' => 'marketing'],
        'adsense_interstitial_enabled' => ['type' => 'boolean', 'group' => 'marketing'],
        'adsense_interstitial_slot_id' => ['type' => 'string', 'group' => 'marketing'],
        'adsense_interstitial_clicks' => ['type' => 'integer', 'group' => 'marketing'],
        'adsense_reward_enabled' => ['type' => 'boolean', 'group' => 'marketing'],
        'adsense_reward_slot_id' => ['type' => 'string', 'group' => 'marketing'],
        'adsense_reward_slot_id_secondary' => ['type' => 'string', 'group' => 'marketing'],
        'adsense_reward_clicks' => ['type' => 'integer', 'group' => 'marketing'],
        'adsense_app_open_slot_id' => ['type' => 'string', 'group' => 'marketing'],
        'adsense_reward_clicks' => ['type' => 'integer', 'group' => 'marketing'],
        'ai_enabled' => ['type' => 'boolean', 'group' => 'ai'],
        'ai_provider' => ['type' => 'string', 'group' => 'ai'],
        'ai_force_real_provider' => ['type' => 'boolean', 'group' => 'ai'],
        'ai_gemini_api_key' => ['type' => 'secret', 'group' => 'ai'],
        'ai_gemini_model' => ['type' => 'string', 'group' => 'ai'],
        'ai_gemini_vision_model' => ['type' => 'string', 'group' => 'ai'],
        'ai_listing_assistant_enabled' => ['type' => 'boolean', 'group' => 'ai'],
        'ai_compass_enabled' => ['type' => 'boolean', 'group' => 'ai'],
        'ai_autoiq_enabled' => ['type' => 'boolean', 'group' => 'ai'],
        'ai_fraud_detection_enabled' => ['type' => 'boolean', 'group' => 'ai'],
        'ai_block_suspicious_chat_images' => ['type' => 'boolean', 'group' => 'ai'],
        'ai_block_scam_messages' => ['type' => 'boolean', 'group' => 'ai'],
        'ai_personalization_enabled' => ['type' => 'boolean', 'group' => 'ai'],
        'ai_job_matching_enabled' => ['type' => 'boolean', 'group' => 'ai'],
        'ai_duplicate_detection_enabled' => ['type' => 'boolean', 'group' => 'ai'],
        'ai_price_recommendation_enabled' => ['type' => 'boolean', 'group' => 'ai'],
        'ai_descriptron_enabled' => ['type' => 'boolean', 'group' => 'ai'],
        'ai_image_optimization_enabled' => ['type' => 'boolean', 'group' => 'ai'],
        'ai_ar_car_features_enabled' => ['type' => 'boolean', 'group' => 'ai'],
        'ai_compass_max_results' => ['type' => 'integer', 'group' => 'ai'],
        'ai_confidence_threshold' => ['type' => 'integer', 'group' => 'ai'],
        'ai_time_savings_min' => ['type' => 'integer', 'group' => 'ai'],
        'ai_time_savings_max' => ['type' => 'integer', 'group' => 'ai'],
        'ai_quality_improvement_max' => ['type' => 'integer', 'group' => 'ai'],
        'ai_seo_optimizer_enabled' => ['type' => 'boolean', 'group' => 'ai'],
        'ai_seo_auto_apply_enabled' => ['type' => 'boolean', 'group' => 'ai'],
        'ai_seo_generate_sitemap' => ['type' => 'boolean', 'group' => 'ai'],
        'ai_seo_audit_interval_minutes' => ['type' => 'integer', 'group' => 'ai'],
        'ai_seo_lookback_days' => ['type' => 'integer', 'group' => 'ai'],
        'ai_seo_max_keywords' => ['type' => 'integer', 'group' => 'ai'],
        'ai_seo_last_run_at' => ['type' => 'string', 'group' => 'ai'],
        'ai_seo_last_score' => ['type' => 'integer', 'group' => 'ai'],
        'ai_seo_last_provider' => ['type' => 'string', 'group' => 'ai'],
        'ai_seo_last_summary' => ['type' => 'string', 'group' => 'ai'],
        'ai_seo_last_keywords' => ['type' => 'json', 'group' => 'ai'],
        'ai_seo_last_actions' => ['type' => 'json', 'group' => 'ai'],
        'app_latest_version' => ['type' => 'string', 'group' => 'app'],
        'app_min_version' => ['type' => 'string', 'group' => 'app'],
        'app_play_store_url' => ['type' => 'string', 'group' => 'app'],
        'app_force_update_msg' => ['type' => 'string', 'group' => 'app'],
        'codecanyon_purchase_code' => ['type' => 'secret', 'group' => 'license'],
        'codecanyon_buyer_username' => ['type' => 'string', 'group' => 'license'],
        'codecanyon_personal_token' => ['type' => 'secret', 'group' => 'license'],
        'license_verified' => ['type' => 'boolean', 'group' => 'license'],
        'license_last_verified' => ['type' => 'string', 'group' => 'license'],
    ],

    'sections' => [
        'general' => [
            'site_name', 'site_tagline', 'site_logo', 'site_favicon', 'site_address',
            'site_currency', 'site_currency_symbol', 'social_facebook', 'social_instagram',
            'social_twitter', 'social_whatsapp', 'social_youtube', 'app_google_play_url',
            'app_store_url', 'maintenance_mode', 'maintenance_title', 'maintenance_message',
            'home_banner_mode', 'home_banner_image_url', 'home_banner_images',
            'home_banner_image_positions', 'home_banner_image_fits', 'home_banner_display_seconds',
            'app_banner_images', 'app_banner_display_seconds', 'home_banner_slide_1_badge',
            'home_banner_slide_1_title', 'home_banner_slide_1_desc', 'home_banner_slide_2_badge',
            'home_banner_slide_2_title', 'home_banner_slide_2_desc', 'home_banner_slide_3_badge',
            'home_banner_slide_3_title', 'home_banner_slide_3_desc',
        ],
        'support' => ['contact_email', 'support_phone', 'support_faqs'],
        'listings' => [
            'listing_moderation_enabled', 'listing_allow_guest_view', 'listing_expiry_days',
            'listing_max_images', 'listing_max_per_user', 'listing_description_min',
            'listing_price_required', 'listing_location_required', 'listing_allow_negotiation',
            'listing_auto_renew', 'listing_allow_bump', 'location_nearby_radius_km',
            'location_default_country', 'free_call_access_limit', 'free_map_access_limit',
            'google_maps_api_key',
        ],
        'featured' => [
            'featured_daily_rate', 'featured_allowed_days', 'payment_gateway',
            'payment_checkout_mode', 'payment_gateway_selection_mode', 'payment_currency',
            'payment_test_mode', 'razorpay_key_id', 'razorpay_key_secret', 'razorpay_base_url',
            'phonepe_merchant_id', 'phonepe_salt_key', 'phonepe_salt_index', 'phonepe_base_url',
            'paytm_mid', 'paytm_merchant_key', 'paytm_website', 'paytm_base_url',
        ],
        'registration' => [
            'registration_enabled', 'email_verification_required', 'phone_verification_required',
            'auth_login_email_enabled', 'auth_login_mobile_enabled', 'auth_register_email_enabled',
            'auth_register_mobile_enabled', 'firebase_auth_domain', 'google_oauth_enabled',
            'google_oauth_client_id', 'google_oauth_client_secret', 'facebook_oauth_enabled',
            'facebook_oauth_app_id', 'facebook_oauth_app_secret',
        ],
        'notifications' => [
            'notification_poll_seconds', 'notification_email_enabled', 'notification_new_message',
            'notification_listing_approved', 'notification_listing_expired',
            'notification_push_enabled', 'notification_sound_url', 'startup_popup_enabled',
            'startup_popup_title', 'startup_popup_message', 'startup_popup_image_url',
            'startup_popup_link_url', 'startup_popup_button_label', 'startup_popup_style',
            'startup_popup_open_new_tab', 'fcm_api_key', 'fcm_project_id',
            'fcm_messaging_sender_id', 'fcm_app_id', 'fcm_vapid_key',
            'fcm_service_account_email', 'fcm_service_account_private_key', 'fcm_server_key',
        ],
        'twa' => [
            'twa_enabled', 'twa_name', 'twa_short_name', 'twa_description', 'twa_start_url',
            'twa_scope', 'twa_display', 'twa_orientation', 'twa_theme_color',
            'twa_background_color', 'twa_navigation_color', 'twa_package_name',
            'twa_sha256_fingerprints', 'twa_icon_url', 'twa_icon_maskable_url',
            'twa_splash_fade_duration', 'twa_app_version_name', 'twa_app_version_code',
            'twa_min_sdk_version', 'twa_signing_key_alias', 'twa_keystore_store_type',
            'twa_keystore_password', 'twa_key_password', 'twa_key_full_name', 'twa_key_org',
            'twa_key_org_unit', 'twa_key_country', 'twa_key_state', 'twa_key_city',
        ],
        'email' => [
            'mail_driver', 'mail_from_name', 'mail_from_address', 'mail_smtp_host',
            'mail_smtp_port', 'mail_smtp_username', 'mail_smtp_password',
            'mail_smtp_encryption', 'mail_mailgun_domain', 'mail_mailgun_secret',
        ],
        'security' => [
            'recaptcha_enabled', 'recaptcha_version', 'recaptcha_site_key',
            'recaptcha_secret_key', 'max_login_attempts', 'login_lockout_minutes',
        ],
        'marketing' => [
            'seo_meta_description', 'seo_meta_keywords', 'seo_robots',
            'seo_google_site_verification', 'seo_bing_site_verification',
            'seo_google_analytics_id', 'facebook_pixel_id', 'og_image_url', 'adsense_enabled',
            'adsense_client_id', 'adsense_slot_id', 'adsense_banner_slot_top',
            'adsense_banner_slot_bottom', 'adsense_banner_slot_guest', 'adsense_native_slot_id',
            'adsense_article_slot_id', 'adsense_display_slot_id', 'adsense_feed_rows_interval',
            'adsense_locations', 'adsense_interstitial_enabled', 'adsense_interstitial_slot_id',
            'adsense_interstitial_clicks', 'adsense_reward_enabled', 'adsense_reward_slot_id',
            'adsense_reward_slot_id_secondary', 'adsense_reward_clicks', 'adsense_app_open_slot_id',
        ],
        'ai' => [
            'ai_enabled', 'ai_provider', 'ai_force_real_provider', 'ai_gemini_api_key',
            'ai_gemini_model', 'ai_gemini_vision_model', 'ai_listing_assistant_enabled',
            'ai_compass_enabled', 'ai_autoiq_enabled', 'ai_fraud_detection_enabled',
            'ai_block_suspicious_chat_images', 'ai_block_scam_messages', 'ai_personalization_enabled',
            'ai_job_matching_enabled', 'ai_duplicate_detection_enabled',
            'ai_price_recommendation_enabled', 'ai_descriptron_enabled',
            'ai_image_optimization_enabled', 'ai_ar_car_features_enabled',
            'ai_compass_max_results', 'ai_confidence_threshold', 'ai_time_savings_min',
            'ai_time_savings_max', 'ai_quality_improvement_max', 'ai_seo_optimizer_enabled',
            'ai_seo_auto_apply_enabled', 'ai_seo_generate_sitemap',
            'ai_seo_audit_interval_minutes', 'ai_seo_lookback_days', 'ai_seo_max_keywords',
        ],
        'app' => ['app_latest_version', 'app_min_version', 'app_play_store_url', 'app_force_update_msg'],
        'license' => [
            'codecanyon_purchase_code', 'codecanyon_buyer_username', 'codecanyon_personal_token',
            'license_verified', 'license_last_verified',
        ],
    ],
];
